---
- name: configure exim4
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root group=root mode=0644
  notify:
    - update exim4 config
    - restart exim4
    - force mail delivery
  with_items:
    - { src: mail/mailname.j2, dest: /etc/mailname }
    - { src: mail/update-exim4.conf.conf.j2, dest: /etc/exim4/update-exim4.conf.conf }
  when: smtp_smarthost is defined

- name: update smarthost auth
  template: src=mail/passwd.client.j2
            dest=/etc/exim4/passwd.client
            owner=root group=Debian-exim mode=0640
  when: smtp_smarthost is defined

- name: set user email aliases
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root group=root mode=0644
  with_items:
    - { src: mail/email-addresses.j2, dest: /etc/email-addresses }
    - { src: mail/aliases.j2, dest: /etc/aliases }
  when: smtp_smarthost is defined
