---
- name: install supervisord
  apt: pkg=supervisor default_release=wheezy-backports state=present

- name: configure supervisord
  template: src=supervisord/supervisord.conf.j2
            dest=/etc/supervisor/supervisord.conf
            owner=root group=root mode=0644
  notify:
    - restart supervisord
