---
- name: set timezone
  copy: content={{ timezone }}
        dest=/etc/timezone
        owner=root group=root mode=0644

- name: set localtime
  copy: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root group=root mode=0644
  notify:
    - restart rsyslog
    - restart cron

- name: intstall ntp
  apt: pkg=ntp state=present

- name: configure ntp
  template: src=time/ntp.conf.j2
            dest=/etc/ntp.conf
            owner=root group=root mode=0644
  notify:
    - restart ntp
