---
- name: add users
  user: name={{ item.user.name }}
        comment="{{ item.user.gecos }}"
        uid={{ item.user.uid }}
        password={{ item.user.password|default("*") }}
        shell=/bin/bash
        groups={{ item.groups }}
        state=present
  with_items: users

- name: update dotfiles
  git: repo={{ item.user.dotfiles }}
       dest=/home/{{ item.user.name }}/.dotfiles
  register: dotfiles
  ignore_errors: yes
  sudo: yes
  sudo_user: "{{ item.user.name }}"
  when: "'dotfiles' in item.user"
  with_items: users

- name: make dotfiles
  shell: make install
         chdir=/home/{{ item.item.user.name }}/.dotfiles
  sudo: yes
  sudo_user: "{{ item.item.user.name }}"
  when: item|changed
  with_items: dotfiles.results

- name: add authorized keys
  authorized_key: user={{ item.0.name }}
                  key="{{ item.1 }}"
                  path=/etc/ssh/keys/{{ item.0.name }}_keys
                  manage_dir=no
                  state=present
  with_subelements:
    - users|attrs('user')|list
    - authorized_keys

- name: remove unknown authorized keys
  file: path={{ item }}
        state=absent
  when: item|basename|rstrip_substring('_keys') not in users|attrs('user')|attrs('name') and
        not (inventory_hostname in groups['gitservers'] and item|basename == 'git_keys')
  with_fileglob:
    - /etc/ssh/keys/*
