---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes

  vars:
    locales:
      - en_US.UTF-8 UTF-8
      - ru_RU.UTF-8 UTF-8
      - ru_RU.KOI8-R KOI8-R
      - ru_RU.CP1251 CP1251
    keyboard_layouts:
      - us
      - ru
    timezone: Europe/Moscow

    users:
      - { user: "{{ user_list.vagrant }}", groups: adm }

    sysctl_additional:
      - { name: vm.swappiness, value: 0 }

    ssh_accept:
      - 10.0.2.2

    mailname: vagrant

  roles:
    - common
