---
apt_repos: []
locales:
  - en_US.UTF-8 UTF-8
keyboard_layouts:
  - us
nameservers:
  - 8.8.8.8
  - 8.8.4.4
  - 2001:4860:4860::8888
  - 2001:4860:4860::8844
unbound_extended_statistics: "no"
timezone: UTC
ntp_servers:
  - 0.debian.pool.ntp.org
  - 1.debian.pool.ntp.org
  - 2.debian.pool.ntp.org
  - 3.debian.pool.ntp.org
users: []
sysctl_additional: []
