---
- name: create postgresql user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ item.db_name|default(item.name) }}
                   password={{ item.db_password }}
  with_items: django_projects
  when: inventory_hostname in groups['postgresqlservers']

- name: create postgresql db
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ item.db_name|default(item.name) }}
                 encoding='{% if locales[0].endswith('UTF-8') %}UTF8{% else %}SQL_ASCII{% endif %}'
                 lc_collate='{{ locales[0].split()[0] }}'
                 lc_ctype='{{ locales[0].split()[0] }}'
                 template='template0'
  with_items: django_projects
  when: inventory_hostname in groups['postgresqlservers']
