---
- name: install postgresql
  apt: pkg={{ item }} state=present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: create sysctl.d files
  copy: dest=/etc/sysctl.d/30postgresql.conf
        content=""
        force=no
        owner=root group=root mode=0644

- name: modify kernel resourses
  sysctl: name={{ item.name }}
          value={{ item.value }}
          sysctl_file=/etc/sysctl.d/30postgresql.conf
          state=present
  with_items:
    - { name: kernel.shmmax, value: "{{ kernel_shmmax }}" }
    - { name: kernel.shmall, value: "{{ kernel_shmall }}" }

- name: configure postgresql
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=postgres group=postgres mode={{ item.mode|default('0644') }}
  with_items:
    - { src: pg_ctl.conf.j2, dest: /etc/postgresql/9.1/main/pg_ctl.conf }
    - { src: pg_hba.conf.j2, dest: /etc/postgresql/9.1/main/pg_hba.conf, mode: '0640' }
    - { src: pg_ident.conf.j2, dest: /etc/postgresql/9.1/main/pg_ident.conf, mode: '0640' }
    - { src: postgresql.conf.j2, dest: /etc/postgresql/9.1/main/postgresql.conf }
  notify:
    - restart postgresql

- name: create postgresql user
  sudo: yes
  sudo_user: postgres
  postgresql_user: name={{ item.name }}
                   password={{ item.password }}
  with_items: postgresql_databases

- name: create postgresql db
  sudo: yes
  sudo_user: postgres
  postgresql_db: name={{ item.name }}
                 encoding="{% if locales[0].endswith('UTF-8') %}UTF8{% else %}SQL_ASCII{% endif %}"
                 lc_collate="{{ locales[0].split()[0] }}"
                 lc_ctype="{{ locales[0].split()[0] }}"
                 template="template0"
  with_items: postgresql_databases
