---
- name: make dirs for virtual hosts
  file: path=/srv/www/{{ item.key }}
        owner=root group=root mode=755
        state=directory
  with_dict: nginx_static_servers

- name: copy ssl certs
  copy: src={{ item.value.ssl_cert }}
        dest=/etc/ssl/localcerts/{{ item.key }}.chained.crt
        owner=root group=root mode=0644
  when: item.value.ssl
  with_dict: nginx_static_servers

- name: copy ssl cert keys
  copy: src={{ item.value.ssl_key }}
        dest=/etc/ssl/localcerts/{{ item.key }}.key
        owner=root group=ssl-cert mode=0640
  when: item.value.ssl
  with_dict: nginx_static_servers

- name: configure virtual hosts
  template: src=static_server.j2
            dest=/etc/nginx/sites-available/{{ item.key }}
            owner=root group=root mode=0644
  with_dict: nginx_static_servers
  notify:
    - reload nginx

- name: enable virtual hosts
  file: src=/etc/nginx/sites-available/{{ item.key }}
        dest=/etc/nginx/sites-enabled/{{ item.key }}
        state=link
  with_dict: nginx_static_servers
  notify:
    - reload nginx
