---
- name: install redis
  apt: pkg=redis-server default_release=wheezy-backports state=present

- name: configure redis
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root group=root mode=0644
  with_items:
    - { src: redis.conf.j2, dest: /etc/redis/redis.conf }
    - { src: sentinel.conf.j2, dest: /etc/redis/sentinel.conf }
  notify:
    - restart redis
