---
- include: ../../common/handlers/main.yml
- include: ../../nginx/handlers/main.yml

- name: upgrade sentry
  shell: /srv/www/{{ sentry_server_name }}/env/bin/sentry --config=/srv/www/{{ sentry_server_name }}/settings/sentry.conf.py upgrade

- name: collect sentry static
  shell: /srv/www/{{ sentry_server_name }}/env/bin/sentry --config=/srv/www/{{ sentry_server_name }}/settings/sentry.conf.py collectstatic  -v0 --noinput

- name: reload sentry web
  shell: supervisorctl pid {{ sentry_server_name }}_web | xargs kill -HUP

- name: restart sentry web
  supervisorctl: name={{ sentry_server_name }}_web state=restarted

- name: restart sentry worker
  supervisorctl: name={{ sentry_server_name }}_worker state=restarted

- name: restart sentry beat
  supervisorctl: name={{ sentry_server_name }}_beat state=restarted
