---
- hosts: vagrant_box
  remote_user: vagrant
  sudo: yes

  vars:
    locales:
      - en_US.UTF-8 UTF-8
      - ru_RU.UTF-8 UTF-8
      - ru_RU.KOI8-R KOI8-R
      - ru_RU.CP1251 CP1251
    keyboard_layouts:
      - us
      - ru
    timezone: Europe/Moscow

    users:
      - user:
          name: vagrant
          password: "$6$ERfXCVxk$mmdpfeit6dZMQrqRxrE2/LNKGKnIp47UuYzJPF3RvOtpT3jgVDF5hHnA1r0pQYg6bwd4pkQlm9yQSa.OdZQtK1"
          email_alias: vagrant
          uid: 1000
          gecos: vagrant
          authorized_keys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
        groups: adm

    nameservers:
      - 10.0.2.3

    sysctl_additional:
      - { name: vm.swappiness, value: 0 }

    ssh_accept:
      - 10.0.2.2

    mailname: vagrant

  roles:
    - common
