---
postgresql_databases: []

postgresql_max_connections: 200
postgresql_checkpoint_segments: 32
postgresql_checkpoint_completion_target: 0.7
postgresql_default_statistics_target: 100

kernel_shmall: "{{ ansible_memtotal_mb * 128 }}"
kernel_shmmax: "{{ kernel_shmall|int() * 4096 }}"
